Ajuste CI/CD para deploy por etapas

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -147,7 +147,7 @@ jobs:
 
           echo "✅ Deploy e atualização do banco de dados realizados com sucesso para ${{ matrix.nome }}"
 
-  deploy:
+  deploy_homolog:
     runs-on: ubuntu-latest
     needs: [deploy_next_prod]
     strategy:
@@ -161,28 +161,12 @@ jobs:
             api: FTP_URL_DBU_000205_HLG
             server: FTP_HOST_PORTALPRODHOMOLOG
 
-          - nome: 000205 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000205
-            password_secret: FTP_PASSWORD_000205
-            dir: ./
-            api: FTP_URL_DBU_000205
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
           - nome: 000347 Homolog
             tipo: ftp
             username_secret: FTP_USERNAME_000347
             password_secret: FTP_PASSWORD_000347
             dir: ./homolog/
             api: FTP_URL_DBU_000347_HLG
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
-          - nome: 000347 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000347
-            password_secret: FTP_PASSWORD_000347
-            dir: ./
-            api: FTP_URL_DBU_000347
             server: FTP_HOST_PORTALPRODHOMOLOG
 
           - nome: 000348 Homolog
@@ -193,28 +177,12 @@ jobs:
             api: FTP_URL_DBU_000348_HLG
             server: FTP_HOST_PORTALPRODHOMOLOG
 
-          - nome: 000348 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000348
-            password_secret: FTP_PASSWORD_000348
-            dir: ./
-            api: FTP_URL_DBU_000348
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
           - nome: 000353 Homolog
             tipo: ftp
             username_secret: FTP_USERNAME_000353
             password_secret: FTP_PASSWORD_000353
             dir: ./homolog/
             api: FTP_URL_DBU_000353_HLG
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
-          - nome: 000353 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000353
-            password_secret: FTP_PASSWORD_000353
-            dir: ./
-            api: FTP_URL_DBU_000353
             server: FTP_HOST_PORTALPRODHOMOLOG
 
           - nome: 000333 Homolog
@@ -225,28 +193,12 @@ jobs:
             api: FTP_URL_DBU_000333_HLG
             server: FTP_HOST_PORTALPRODHOMOLOG
 
-          - nome: 000333 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000333
-            password_secret: FTP_PASSWORD_000333
-            dir: ./
-            api: FTP_URL_DBU_000333
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
           - nome: 000335 Homolog
             tipo: ftp
             username_secret: FTP_USERNAME_000335
             password_secret: FTP_PASSWORD_000335
             dir: ./homolog/
             api: FTP_URL_DBU_000335_HLG
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
-          - nome: 000335 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000335
-            password_secret: FTP_PASSWORD_000335
-            dir: ./
-            api: FTP_URL_DBU_000335
             server: FTP_HOST_PORTALPRODHOMOLOG
 
           - nome: 000226 Homolog
@@ -257,20 +209,141 @@ jobs:
             api: FTP_URL_DBU_000226_HLG
             server: FTP_HOST_PORTALPRODHOMOLOG
 
-          - nome: 000226 Prod
-            tipo: ftp
-            username_secret: FTP_USERNAME_000226
-            password_secret: FTP_PASSWORD_000226
-            dir: ./
-            api: FTP_URL_DBU_000226
-            server: FTP_HOST_PORTALPRODHOMOLOG
-
           - nome: 000234 Homolog
             tipo: ftp
             username_secret: FTP_USERNAME_000234_HLG
             password_secret: FTP_PASSWORD_000234_HLG
             dir: ./
             api: FTP_URL_DBU_000234_HLG
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          # - nome: 000240 Homolog
+          #   tipo: sftp
+          #   port: FTP_PORT_000240
+          #   username_secret: FTP_USERNAME_000240
+          #   password_secret: FTP_PASSWORD_000240
+          #   dir: /var/www/html/homolog/
+          #   api: FTP_URL_DBU_000240
+          #   server: FTP_HOST_000240
+
+    steps:
+      - name: 🚚 Get latest code
+        uses: actions/checkout@v4
+
+      - name: 📂 Sync files ${{ matrix.nome }}
+        if: matrix.tipo == 'ftp'
+        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
+        with:
+          server: ${{ secrets[matrix.server] }}
+          username: ${{ secrets[matrix.username_secret] }}
+          password: ${{ secrets[matrix.password_secret] }}
+          server-dir: ${{ matrix.dir }}
+          exclude: |
+            **/.git*
+            **/.git*/**
+            webservice/especificos_
+            webservice/especificos_/**
+        
+      - name: 📂 Sync via SFTP ${{ matrix.nome }}
+        if: matrix.tipo == 'sftp'
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ secrets[matrix.server] }}
+          username: ${{ secrets[matrix.username_secret] }}
+          password: ${{ secrets[matrix.password_secret] }}
+          port: ${{ secrets[matrix.port] }}
+          source: ./
+          target: ${{ matrix.dir }}
+
+      - name: 🔗 Call API after deploy ${{ matrix.nome }}
+        run: |
+          echo "📡 Chamando API para ${{ matrix.nome }}"
+
+          RESPONSE_CODE=$(curl -X POST "${{ secrets[matrix.api] }}${{ secrets.SUFIXO_DBU_API }}" \
+            -H "Content-Type: application/json" \
+            -H "Dbutoken: ${{ secrets.DBU_API_TOKEN }}" \
+            -d '{"status": "success", "message": "FTP deploy complete"}' \
+            -w "%{http_code}" -o response.txt -s)
+
+          echo "🔍 HTTP Response Code: $RESPONSE_CODE"
+
+          RESPONSE_BODY=$(cat response.txt)
+          echo "📄 API Response:"
+          echo "$RESPONSE_BODY"
+
+          if [ "$RESPONSE_CODE" -ne 200 ]; then
+            echo "❌ API call failed with status code $RESPONSE_CODE"
+            exit 1
+          fi
+
+          if [[ "$RESPONSE_BODY" != *"Atualizacao de estrutura procedimentos e funcoes do banco de dados concluida"* ]]; then
+            echo "❌ Resposta inesperada da API!"
+            echo "🔎 Esperado: 'Atualizacao de estrutura procedimentos e funcoes do banco de dados concluida'"
+            exit 1
+          fi
+
+          echo "✅ Deploy e atualização do banco de dados realizados com sucesso para ${{ matrix.nome }}"
+  
+  deploy_prod:
+    runs-on: ubuntu-latest
+    needs: [deploy_homolog]
+    strategy:
+      matrix:
+        include:
+          - nome: 000205 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000205
+            password_secret: FTP_PASSWORD_000205
+            dir: ./
+            api: FTP_URL_DBU_000205
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          - nome: 000347 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000347
+            password_secret: FTP_PASSWORD_000347
+            dir: ./
+            api: FTP_URL_DBU_000347
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          - nome: 000348 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000348
+            password_secret: FTP_PASSWORD_000348
+            dir: ./
+            api: FTP_URL_DBU_000348
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          - nome: 000353 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000353
+            password_secret: FTP_PASSWORD_000353
+            dir: ./
+            api: FTP_URL_DBU_000353
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          - nome: 000333 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000333
+            password_secret: FTP_PASSWORD_000333
+            dir: ./
+            api: FTP_URL_DBU_000333
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          - nome: 000335 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000335
+            password_secret: FTP_PASSWORD_000335
+            dir: ./
+            api: FTP_URL_DBU_000335
+            server: FTP_HOST_PORTALPRODHOMOLOG
+
+          - nome: 000226 Prod
+            tipo: ftp
+            username_secret: FTP_USERNAME_000226
+            password_secret: FTP_PASSWORD_000226
+            dir: ./
+            api: FTP_URL_DBU_000226
             server: FTP_HOST_PORTALPRODHOMOLOG
 
           - nome: 000234 Prod
